runtime: python27
api_version: 1
threadsafe: false

skip_files:
- ^(.*/)?#.*#$
- ^(.*/)?.*~$
- ^(.*/)?.*\.py[co]$
- ^(.*/)?.*/RCS/.*$
- ^(.*/)?\..*$
- gui
- references
- README\.md
- vacancy\.js

handlers:
- url: /(.*\.(gif|png|jpg|ico|css|js))
  static_files: \1
  upload: .*\.(gif|png|jpg|ico|css|js)
- url: /(scrape_yearterm|(map|data)\.json)?
  script: index.app
  secure: always
- url: /scrape
  script: scrape.py
  secure: always
