application: antscoper
version: 1

runtime: python27
api_version: 1
threadsafe: true

skip_files:
- AntScope
- __pycache__
- ./*.ipynb
- ./*.js
- ./*.md

handlers:
- url: /.*
  script: main.app
  secure: always
